# Modal
MODAL_APP_NAME = "asr-thesis"
MODAL_GPU = "A100"
MODAL_MEMORY = 24576
MODAL_TIMEOUT = 600
MODAL_CONTAINER_IDLE_TIMEOUT = 120

# Whisper
WHISPER_MODEL = "large-v3"
WHISPER_LANGUAGE = "vi"  # Force Vietnamese detection
ASR_DEVICE = "cuda"

# VAD (Energy-based)
VAD_THRESHOLD = 0.01
MIN_SILENCE_DURATION = 0.6
MAX_BUFFER_DURATION = 8.0

# NLLB Translation
NLLB_MODEL = "facebook/nllb-200-3.3B"
NLLB_SRC_LANG = "vie_Latn"
NLLB_TGT_LANG = "eng_Latn"
NLLB_DEVICE = "cuda"

# Audio
SAMPLE_RATE = 16000
